### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by LujanLisandro** [MOXHARTZ/mx-discordtool#1]
I don't know if it's possible, but it would be interesting if the discord was associated with the characters, to be able to use the /user @discordtag without the person being online, it would be a facility for many things

**Comment by MOXHARTZ** [comment]
I had a few ideas in mind for doing this. But discord had to be added to the user table as an extra and conditions such as the user had to enter the server at least once. Well, that's why I didn't add it. Maybe it will be added in the future.

**Comment by LujanLisandro** [comment]
Of course, it would seem logical to me that you have to enter for the bot to make the association, thank you very much for taking it into account, the bot is already very useful
